version: ""

formatter: markdown table

name: terraform-aws-guard-duty-notifications

content: |-
  # terraform-aws-guard-duty-notifications
  GitHub: [StratusGrid/terraform-aws-guard-duty-notifications](https://github.com/StratusGrid/terraform-aws-guard-duty-notifications/)
  
  This module creates SNS topics for three tiers of GuardDuty findings, EventBridge rules and triggers to add findings to the SNS topics, and a KMS key and alias used to encrypt data sent to the SNS topics.

  Currently, subscriptions to the topics are not managed in this module.

  ## Example
  ```hcl
  {{ include "examples/example1.tfnot" }}
  ```
  
  ## StratusGrid Standards we assume
  - All resource names and name tags shall use `_` and not `-`s
  - The old naming standard for common files such as inputs, outputs, providers, etc was to prefix them with a `-`, this is no longer true as it's not POSIX compliant. Our pre-commit hooks will fail with this old standard.
  - StratusGrid generally follows the TerraForm standards outlined [here](https://www.terraform-best-practices.com/naming)

  ---
  {{ .Requirements }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}
  ---
  Note, manual changes to the README will be overwritten when the documentation is updated. To update the documentation, run `terraform-docs -c .config/.terraform-docs.yml`
sections:
  show:
    - requirements
    - resources
    - inputs
    - outputs

sort:
  enabled: true
  by: name

output:
  file: README.md
  mode: replace